name: toolbox-env
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - beautifulsoup4=4.11.1=py39h06a4308_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bs4=4.11.1=hd3eb1b0_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2023.05.30=h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.0.4=py39h06a4308_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - confection=0.0.4=py39hb070fc8_0
  - cymem=2.0.6=py39h295c915_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dnspython=2.2.1=py39h06a4308_0
  - email-validator=1.2.1=py39h06a4308_0
  - email_validator=1.2.1=hd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=pyhd8ed1ab_1
  - krb5=1.19.2=hac12032_0
  - langcodes=3.3.0=pyhd8ed1ab_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=7.84.0=h91b91d3_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.1.0=h8d9b700_16
  - libnghttp2=1.46.0=hce63b2e_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=14.0.4=he0ac6c6_0
  - lxml=4.9.1=py39h1edc446_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py39h7f8727e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - murmurhash=1.0.7=py39h295c915_0
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1t=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pathy=0.6.2=pyhd8ed1ab_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - preshed=3.0.6=py39h295c915_0
  - protobuf=3.20.3=py39h6a678d5_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.13=haa1d7c7_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=pyhd8ed1ab_1
  - rhash=1.4.1=h3c74f83_1
  - shellingham=1.5.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=pyhd8ed1ab_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - spacy-legacy=3.0.10=pyhd8ed1ab_0
  - spacy-loggers=1.0.3=pyhd8ed1ab_0
  - spacy-model-fr_core_news_md=3.4.0=pyhd8ed1ab_0
  - spacy-model-fr_core_news_sm=3.4.0=pyhd8ed1ab_0
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - typer=0.4.2=pyhd8ed1ab_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wasabi=0.10.0=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - accelerate==0.22.0
      - asttokens==2.4.1
      - babel==2.12.1
      - blis==0.7.8
      - bottleneck==1.3.5
      - bpemb==0.3.3
      - catalogue==2.0.8
      - certifi==2022.9.14
      - cloudpickle==2.2.0
      - cmake==3.26.4
      - conllu==4.5.2
      - contourpy==1.0.5
      - cryptography==37.0.1
      - cycler==0.11.0
      - dawg-python==0.7.2
      - decorator==5.1.1
      - deprecated==1.2.13
      - dill==0.3.5.1
      - docopt==0.6.2
      - es-core-news-sm
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - filelock==3.8.0
      - flair==0.11.3
      - flask==2.2.2
      - flask-babel==3.1.0
      - flask-wtf==1.0.1
      - fonttools==4.37.3
      - fr-core-news-lg==3.4.0
      - fsspec==2023.9.0
      - ftfy==6.1.1
      - future==0.18.2
      - gdown==4.4.0
      - gensim==4.2.0
      - geographiclib==1.52
      - geopy==2.2.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - grimbert==0.1.1
      - huggingface-hub==0.16.4
      - hyperopt==0.2.7
      - importlib-metadata==3.10.1
      - iniconfig==2.0.0
      - ipython==8.17.2
      - itsdangerous==2.1.2
      - janome==0.4.2
      - jedi==0.19.1
      - joblib==1.2.0
      - jsonpickle==3.0.2
      - keybert==0.7.0
      - kiwisolver==1.4.4
      - konoha==4.6.5
      - langdetect==1.0.9
      - libwapiti==0.2.1
      - lit==16.0.6
      - markdown-it-py==3.0.0
      - matplotlib==3.6.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - more-itertools==10.1.0
      - mpld3==0.3
      - mpmath==1.3.0
      - munch==2.5.0
      - nameparser==1.1.2
      - neleval==3.1.1
      - networkx==2.8.6
      - nltk==3.8.1
      - numexpr==2.8.3
      - numpy==1.23.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.52
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.8.0.76
      - overrides==3.1.0
      - pandas==2.0.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pillow==9.2.0
      - pip==23.3.1
      - pluggy==1.3.0
      - pptree==3.1
      - prompt-toolkit==3.0.39
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - py4j==0.10.9.7
      - pydantic==1.9.0
      - pygments==2.15.1
      - pymorphy2==0.9.1
      - pymorphy2-dicts-ru==2.4.417127.4579844
      - pytest==7.4.1
      - pytz==2023.3
      - pyvis==0.3.2
      - pyyaml==6.0
      - regex==2022.9.13
      - renard-pipeline==0.3.0
      - rich==13.6.0
      - sacred==0.8.4
      - sacremoses==0.0.53
      - safetensors==0.3.3
      - scikit-learn==1.3.2
      - scipy==1.9.1
      - segtok==1.5.11
      - semtagger==4.0.0a2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.95
      - seqeval==1.2.2
      - setuptools==63.4.1
      - smmap==5.0.1
      - spacy==3.4.1
      - sqlitedict==2.0.0
      - srsly==2.4.3
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.8.10
      - thinc==8.1.0
      - threadpoolctl==3.1.0
      - tibert==0.2.3
      - tokenizers==0.12.1
      - tomli==2.0.1
      - torch==2.1.0
      - torchvision==0.16.0
      - traitlets==5.13.0
      - transformers==4.33.0
      - triton==2.1.0
      - tzdata==2023.3
      - wcwidth==0.2.5
      - werkzeug==2.2.2
      - wikipedia-api==0.5.4
      - wrapt==1.14.1
      - wtforms==3.0.1
      - zipp==3.8.1
